# Generated by Django 3.0.4 on 2020-04-10 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sutrofm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='playing_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playing_party', to='sutrofm.QueueItem'),
        ),
        migrations.AlterField(
            model_name='queueitem',
            name='artist_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='queueitem',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
