# Generated by Django 3.0.4 on 2020-04-20 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sutrofm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='last_manager_check_in',
        ),
        migrations.RemoveField(
            model_name='party',
            name='last_manager_uuid',
        ),
        migrations.RemoveField(
            model_name='party',
            name='users',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parties',
        ),
        migrations.DeleteModel(
            name='UserPartyPresence',
        ),
    ]
