# Generated by Django 3.0.4 on 2020-05-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sutrofm', '0002_auto_20200420_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='theme',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
